---
title: "garch_simulations"
author: "Hugo Belzil"
date: "2024-11-11"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# A GARCH(1,1) Process simulation

```{r,include=FALSE}
library(evir)
library(ggplot2)
set.seed(42)
alpha_0 = 1/2
alpha_1 = 0.1
beta_1 = 0.15     #parameters of the GARCH process
n = 300 #length of the time series

sigma_1 = 1 #first volatility

innovations = rnorm(n,0,1)

volatilities = numeric(n)
x_t = numeric(n)

x_t[1]=sigma_1*innovations[1]
volatilities[1]=sigma_1

for (i in 2:n){
  volatilities[i]=sqrt(alpha_0+alpha_1*(innovations[i-1])^2+beta_1*(volatilities[i-1])^2)
  x_t[i]=innovations[i]*volatilities[i]
}

#plot(x_t,type='l',main = "Simulated Garch Process",xlab="Time t", ylab='X_t')

x_t = data.frame(Time = 1:length(x_t),Value=x_t)

```
```{r}
options(repr.plot.width=8, repr.plot.height=5)
ggplot(x_t, aes(x = Time, y = Value)) +
  geom_line(color = "blue", size = 0.5) +                
  labs(title = "Simulated GARCH(1,1) Process", x = "Time", y = expression(X[t])) +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, size = 14),
    axis.title = element_text(size = 12),
    axis.text = element_text(size = 10)
  ) +
  # Add annotation with GARCH parameters using Greek letters
  annotate("text", x = max(x_t$Time) * 0.95, y = max(x_t$Value) * 0.95, 
           label = bquote(alpha[0] == .(alpha_0) * "," ~ alpha[1] == .(alpha_1) * "," ~ beta[1] == .(beta_1)),
           hjust = 1, vjust = 1, size = 4, color = "black",
           fontface = "italic")

``` 